### PR TITLE
[WIP] Fixes for GHC 8.2.1

### PR DESCRIPTION
**Pull request by k-bx**
Changes done in this PR:

- fixes needed to build under GHC 8.2.1
- updated travis config due to latest [docs](https://docs.haskellstack.org/en/stable/travis_ci/)
- removal of some warnings. I checked that code still builds under latest 4 GHC versions. Tests fail for me, but they fail same way as before

### CODE REVIEW

**Comment by k-bx** [comment]
@markhibberd so, apparently Riak is dead, and download links are not working anymore. Any suggestions what to do? Would we host it somewhere maybe?

**Comment by tmcgilchrist** [comment]
@k-bx Could we use the download links available in github? That should work at least until it's clear who is hosting the official supported version in the future and should cover us for the versions we already officially support.

eg https://github.com/basho/riak/archive/riak-2.2.2.zip

Might be simpler to split this out into a fix for the riak download issue and then another for the gcc 8.2 changes. Thanks for taking the time to look into it. :-)

**Comment by k-bx** [comment]
@tmcgilchrist I actually tried github in one of my last attempts, but it still fails upon install. If you manually download that riak and run "make rel" as it previously did, it'd still fail, since more dependencies are non-available. We need some way to download pre-built executable, maybe via some apt sources.

**Comment by k-bx** [comment]
`make` just failed for me with:

```
Pulling merge_index from {git,"git://github.com/basho/merge_index.git",
                              {tag,"2.0.4"}}
Cloning into 'merge_index'...
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> merge_index (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> riak_control (get-deps)
Pulling erlydtl from {git,"git://github.com/erlydtl/erlydtl.git","d20b53f0"}
Cloning into 'erlydtl'...
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> erlydtl (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> riaknostic (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> yokozuna (get-deps)
Pulling kvc from {git,"git://github.com/etrepum/kvc.git",{tag,"v1.5.0"}}
Cloning into 'kvc'...
Pulling ibrowse from {git,"git://github.com/cmullaparthi/ibrowse.git",
                          {tag,"v4.0.2"}}
Cloning into 'ibrowse'...
Pulling fuse from {git,"git@github.com:jlouis/fuse.git",{tag,"v2.1.0"}}
Cloning into 'fuse'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR: sh(git clone -n git@github.com:jlouis/fuse.git fuse)
failed with return code 128 and the following output:
Cloning into 'fuse'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

ERROR: 'get-deps' failed while processing /home/ubuntu/tmp/riakdownload/riak-riak-2.2.3/deps/yokozuna: rebar_abort
make: *** [deps] Error 1
```

Btw, I've removed riak installation for now in this PR (commented out), I think we should go without it in Travis and fix in separate issue

**Comment by k-bx** [comment]
@tmcgilchrist any idea what caused https://travis-ci.org/markhibberd/riak-haskell-client/jobs/266700677 to fail? I can't figure from the log

**Comment by tmcgilchrist** [comment]
Can't see anything, I've restarted the build fingers crossed.

**Comment by k-bx** [comment]
Hmm

**Comment by markhibberd** [comment]
If you rebase onto master the link should be fixed. We just moved the repository to somewhere more shared.

**Comment by k-bx** [comment]
@markhibberd ok, so 7.10.3 fails for no clear reason, I would reset cache if it's possible in travis UI, maybe some problems there. macOS isn't able to install compiler. Other then that – everything looks good (well, except it doesn't run tests and installs riak yet, but there's a hope it'll be resolved eventually)

Do you think this is ok to be reviewed/merged or is there anything else I should do? Thanks.

**Comment by k-bx** [comment]
@markhibberd sorry for pinging. What are your current thoughts on this? Thanks.

**Comment by tmcgilchrist** [comment]
I've partially restored the CI builds so if you rebase this on top and keep my changes to `.travis.yml` it should build. @k-bx

**Comment by k-bx** [comment]
@tmcgilchrist wow, that's a lot of scripting there. Travis config I've used mentions that we need `sudo: false` in order to use caching. I'll re-open a new PR to make a lightweight change adding GHC 8.2.1 support instead of the approach I tried

**Pull request closed without merging**
